set linebreak
set wrap
" 行号和标尺
set number
set ruler
" 设置竖线
set cuc
set cul

" 在查找时忽略大小写
set ignorecase
set incsearch
set hlsearch

" 制表符
set tabstop=4
set expandtab
set smarttab
set shiftwidth=4
set softtabstop=4

set laststatus=2
set t_Co=256

" vundle----------------------------------------
set nocompatible                " be iMproved
filetype off                    " required!
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

"--------------------------------------------------------
" How to install plugin ?
" BundleInstall
" BundleInstall!
" BundleInstall plugin_name
"
" let Vundle manage Vundle
Bundle 'gmarik/vundle'

" original repos on github
Bundle 'kien/ctrlp.vim'
Bundle 'sukima/xmledit'
Bundle 'sjl/gundo.vim'
Bundle 'jiangmiao/auto-pairs'
Bundle 'klen/python-mode'
Bundle 'Valloric/ListToggle'
Bundle 'scrooloose/syntastic'
Bundle 't9md/vim-quickhl'
Bundle 'scrooloose/nerdcommenter'
Bundle 'bling/vim-airline'

" tagbar
Bundle 'majutsushi/tagbar'
nmap <F8> :TagbarToggle<CR>

" nerdtree
Bundle 'scrooloose/nerdtree'
let NERDTreeWinPos='left'
let NERDTreeWinSize=30
map <F2> :NERDTreeToggle<CR>

"..................................
" vim-scripts repos
Bundle 'YankRing.vim'
Bundle 'vcscommand.vim'
Bundle 'taglist.vim'
Bundle 'EasyGrep'

filetype plugin indent on
" ---------------------------------------------

" ColorTheme
syntax enable
Bundle 'tomasr/molokai'
let g:molokai_original = 1
set background=dark
set t_Co=256
colorscheme molokai
